# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-08 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True, unique=True)),
                ('company_ode', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('company_type', models.CharField(blank=True, max_length=60, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=80, null=True)),
                ('state', models.CharField(blank=True, max_length=90, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=90, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_name', models.CharField(blank=True, max_length=90, null=True)),
                ('peroid_frequency', models.CharField(blank=True, choices=[(b'Monthly', b'Monthly'), (b'Quarterly', b'Quarterly'), (b'Half yearly', b'Half yearly'), (b'Yearly', b'Yearly')], max_length=90, null=True)),
                ('financial_management_system', models.CharField(blank=True, max_length=90, null=True)),
                ('fiscal_start_month', models.DateField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('endclient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audtech_analytics.EndClient')),
            ],
        ),
        migrations.CreateModel(
            name='FinalTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('engangement', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('status_op_posted_unposted', models.CharField(blank=True, max_length=200, null=True)),
                ('type_regular', models.CharField(blank=True, max_length=200, null=True)),
                ('div_code', models.CharField(blank=True, max_length=200, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('sr_no', models.CharField(blank=True, max_length=100, null=True)),
                ('tr_code', models.CharField(blank=True, max_length=200, null=True)),
                ('doc_no', models.CharField(blank=True, max_length=200, null=True)),
                ('acct_category', models.CharField(blank=True, max_length=200, null=True)),
                ('main_acct_code', models.CharField(blank=True, max_length=200, null=True)),
                ('main_acct_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_acct_code', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_acct_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dr_gl_curr_code', models.CharField(blank=True, max_length=200, null=True)),
                ('cr_gl_curr_code', models.CharField(blank=True, max_length=200, null=True)),
                ('tr_curr_code', models.CharField(blank=True, max_length=200, null=True)),
                ('dr_in_fc', models.CharField(blank=True, max_length=200, null=True)),
                ('cr_in_fc', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('authorised_by', models.CharField(blank=True, max_length=200, null=True)),
                ('auto_manual', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OriginalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('engangement', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('c1', models.CharField(blank=True, max_length=200, null=True)),
                ('c2', models.CharField(blank=True, max_length=200, null=True)),
                ('c3', models.CharField(blank=True, max_length=200, null=True)),
                ('c4', models.CharField(blank=True, max_length=200, null=True)),
                ('c5', models.CharField(blank=True, max_length=200, null=True)),
                ('c6', models.CharField(blank=True, max_length=200, null=True)),
                ('c7', models.CharField(blank=True, max_length=200, null=True)),
                ('c8', models.CharField(blank=True, max_length=200, null=True)),
                ('c9', models.CharField(blank=True, max_length=200, null=True)),
                ('c10', models.CharField(blank=True, max_length=200, null=True)),
                ('c11', models.CharField(blank=True, max_length=200, null=True)),
                ('c12', models.CharField(blank=True, max_length=200, null=True)),
                ('c13', models.CharField(blank=True, max_length=200, null=True)),
                ('c14', models.CharField(blank=True, max_length=200, null=True)),
                ('c15', models.CharField(blank=True, max_length=200, null=True)),
                ('c16', models.CharField(blank=True, max_length=200, null=True)),
                ('c17', models.CharField(blank=True, max_length=200, null=True)),
                ('c18', models.CharField(blank=True, max_length=200, null=True)),
                ('c19', models.CharField(blank=True, max_length=200, null=True)),
                ('c20', models.CharField(blank=True, max_length=200, null=True)),
                ('c21', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
