# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audtech_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='CreditAmount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='CreditAmountFC',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='DebitAmount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='DebitAmountFC',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
