# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audtech_analytics', '0003_auto_20190206_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='CreditAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='CreditAmountFC',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='DebitAmountFC',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='DocumentHeaderText',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
