# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-13 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audtech_analytics', '0005_auto_20190212_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltable',
            name='DivisionCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
