# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(blank=True, max_length=50, null=True)),
                ('erp', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Financial System')),
                ('transaction_type', models.CharField(blank=True, max_length=200, null=True)),
                ('final_field', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Audtech Field')),
                ('source_filed', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'System Field')),
                ('column_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'default_permissions': (),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mapping2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('Audtech_field', models.CharField(blank=True, max_length=50, null=True)),
                ('Input_field', models.CharField(blank=True, max_length=50, null=True)),
                ('column_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'default_permissions': (),
                'managed': True,
            },
        ),
    ]
